/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sparkhacks;

/**
 *
 * @author Anshpreet
 */
public class Homepage extends javax.swing.JFrame {

    /**
     * Creates new form Homepage
     */
    public Homepage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBlue = new javax.swing.JPanel();
        article2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Summary2 = new javax.swing.JTextArea();
        panelBlue1 = new javax.swing.JPanel();
        article1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Summary1 = new javax.swing.JTextArea();
        panelPurple = new javax.swing.JPanel();
        btnLive = new javax.swing.JButton();
        btnConnect = new javax.swing.JButton();
        btnQuiz = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBlue.setBackground(new java.awt.Color(4, 4, 150));

        article2.setBackground(new java.awt.Color(0, 0, 204));
        article2.setFont(new java.awt.Font("Bangla MN", 0, 15)); // NOI18N
        article2.setForeground(new java.awt.Color(204, 255, 255));
        article2.setText("Virgin Galactic's Historic Space Trip Heralds a Coming Age of New US Human Spaceflight Leaps");

        Summary2.setBackground(new java.awt.Color(0, 0, 204));
        Summary2.setColumns(20);
        Summary2.setFont(new java.awt.Font("Lantinghei SC", 0, 13)); // NOI18N
        Summary2.setForeground(new java.awt.Color(255, 255, 255));
        Summary2.setRows(5);
        Summary2.setText("Virgin Galactic just brought human spaceflight back to American soil after a seven-year hiatus, and other private companies are\n poised to make some giant leaps of their own.  \nVirgin's VSS Unity suborbital spaceliner soared to a maximum altitude of 51.4 miles (82.7 kilometers) during a rocket-powered\ntest flight over California's Mojave Desert yesterday (Dec. 13). \nRead more: \nhttps://www.space.com/42737-virgin-galactic-human-spaceflight-milestone.html\n");
        jScrollPane1.setViewportView(Summary2);

        panelBlue1.setBackground(new java.awt.Color(4, 4, 150));

        article1.setBackground(new java.awt.Color(0, 0, 204));
        article1.setFont(new java.awt.Font("Bangla MN", 0, 15)); // NOI18N
        article1.setForeground(new java.awt.Color(204, 255, 255));
        article1.setText("Canadian astronaut launches on first trip to space station ");

        Summary1.setBackground(new java.awt.Color(0, 0, 204));
        Summary1.setColumns(20);
        Summary1.setFont(new java.awt.Font("Lantinghei SC", 1, 13)); // NOI18N
        Summary1.setForeground(new java.awt.Color(255, 255, 255));
        Summary1.setRows(5);
        Summary1.setText("Monday, December 3, 2018, 5:06 PM \t\nCanadian astronaut David Saint-Jacques is now on v\nery his first adventure in space! Watch again as he lifts off on his journey, and tune in live to see his arrival \nat the International Space Station!\nAfter over nine years of training, and anticipation, another member of Canada's astronaut core is finally in space.\nRead more:\nhttps://www.theweathernetwork.com/news/articles/david-saint-jacques-canadian-astronaut-launches-on-first-trip-to-\ninternational-space-station/118009\n");
        jScrollPane2.setViewportView(Summary1);

        javax.swing.GroupLayout panelBlue1Layout = new javax.swing.GroupLayout(panelBlue1);
        panelBlue1.setLayout(panelBlue1Layout);
        panelBlue1Layout.setHorizontalGroup(
            panelBlue1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBlue1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBlue1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(article1, javax.swing.GroupLayout.PREFERRED_SIZE, 505, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(5818, Short.MAX_VALUE))
        );
        panelBlue1Layout.setVerticalGroup(
            panelBlue1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBlue1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(article1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(335, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelBlueLayout = new javax.swing.GroupLayout(panelBlue);
        panelBlue.setLayout(panelBlueLayout);
        panelBlueLayout.setHorizontalGroup(
            panelBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBlueLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(article2, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(panelBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelBlueLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelBlue1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        panelBlueLayout.setVerticalGroup(
            panelBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBlueLayout.createSequentialGroup()
                .addContainerGap(300, Short.MAX_VALUE)
                .addComponent(article2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
            .addGroup(panelBlueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelBlueLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelBlue1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        panelPurple.setBackground(new java.awt.Color(102, 0, 204));
        panelPurple.setForeground(new java.awt.Color(0, 51, 204));

        btnLive.setText("LIVE ");
        btnLive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLiveActionPerformed(evt);
            }
        });

        btnConnect.setText("Connect");
        btnConnect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectActionPerformed(evt);
            }
        });

        btnQuiz.setText("Quiz");
        btnQuiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuizActionPerformed(evt);
            }
        });

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPurpleLayout = new javax.swing.GroupLayout(panelPurple);
        panelPurple.setLayout(panelPurpleLayout);
        panelPurpleLayout.setHorizontalGroup(
            panelPurpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPurpleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLive)
                .addGap(72, 72, 72)
                .addComponent(btnConnect)
                .addGap(90, 90, 90)
                .addComponent(btnQuiz)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogin)
                .addGap(28, 28, 28))
        );
        panelPurpleLayout.setVerticalGroup(
            panelPurpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPurpleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPurpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLive)
                    .addComponent(btnConnect)
                    .addComponent(btnQuiz)
                    .addComponent(btnLogin))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBlue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelPurple, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelPurple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelBlue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuizActionPerformed
       // new quiz().setVisible(true);
    }//GEN-LAST:event_btnQuizActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
       // new login().setVisible(true);
        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnConnectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectActionPerformed
       // new connect().setVisible(true);
    }//GEN-LAST:event_btnConnectActionPerformed

    private void btnLiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLiveActionPerformed
       // new live().setVisible(true);
    }//GEN-LAST:event_btnLiveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Summary1;
    private javax.swing.JTextArea Summary2;
    private javax.swing.JLabel article1;
    private javax.swing.JLabel article2;
    private javax.swing.JButton btnConnect;
    private javax.swing.JButton btnLive;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnQuiz;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel panelBlue;
    private javax.swing.JPanel panelBlue1;
    private javax.swing.JPanel panelPurple;
    // End of variables declaration//GEN-END:variables
}
